config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: [:new, :show, :create] do
    resources :movies, only: [:create]
    member do
      get 'results', to: "movies#results"
      get 'search', to: "movies#search"
    end
  end
  resources :movies, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :comment, presence: true, length: { minimum: 6 }
  has_many :movies, dependent: :destroy
  # validates_uniqueness_of :movie_id, scope: [:list_id]
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :list
  validates :title, :poster_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies.order(created_at: :desc)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :img_url, :photo, :comment)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def results
  end

  def search
    require 'open-uri'

    keyword = params[:keyword]
    url = "http://www.omdbapi.com/?s=#{keyword}&type=movie&apikey=#{ENV['OMDB_KEY']}"

    response = JSON.parse(URI.open(url).read)

    @movies = []

    response['Search'].each do |movie|
      @movies << {
        title: movie['Title'],
        poster_url: movie['Poster'],
        year: movie['Year']
      }
    end

    @movie = Movie.new
    @list = List.find(params[:id])

    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # create a new movie
  def create
    @list = List.find(params[:list_id])
    @movie = Movie.new(movie_params)
    @movie.list = @list
    @movie.save!
    redirect_to list_path(@list)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @list_id = @movie.list_id
    @movie.destroy
    redirect_to list_path(@list_id)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :poster_url, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="background primary">
  <%= render "shared/navbar" %>
  <div class="content-container">
    <h1>Looking for a good movie to watch?</h1>
    <p>Welcome to GrabYourPopcorn.com, your ultimate guide for anything movie-related!</p>
    <p>Feel free to browse through the recommandations or create your own watch list.
    <h3 id="highlight">Suggestions</h3>
    <div class="container-fluid cards-container">
      <div class="row text-center flex-nowrap">
        <% @lists.each do |list| %>
          <%= link_to list_path(list.id), class: "link" do %>
            <div class="col-3 list-card mr-3" style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_url('cinema.jpg') %>)">
              <h5 class="card-title text-center align-center"><%= list.name %></h5>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/lists/new.html.erb
<div class="background secondary">
  <%= render "shared/navbar" %>
  <div class="form-container">
    <h2>Create a new watchlist</h2>

    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name, input_html: { autocomplete: 'off' } %>
      <%= f.input :comment, input_html: { autocomplete: 'off' } %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create", class: 'btn btn-block btn-secondary' %>
    <% end %>

    <%= link_to "Back", root_path, class:"btn btn-block btn-outline-secondary" %>
  </div>
</div>

app/views/lists/search.html.erb
<div class="background secondary">
  <%= render "shared/navbar" %>

  <%= %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_url('cinema.jpg') %>)">
  <%= render "shared/navbar" %>
  <div class="banner-content">
    <h1><%= @list.name %></h1>
    <div id="comment" class="container my-2">
      <p><%= @list.comment %></p>
      <%= link_to "Add a movie", results_list_path(@list.id), class: "btn btn-primary mt-2" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-lg-3 col-md-4 col-sm-6 py-3 d-flex align-items-stretch justify-content-center">
        <div class="card">
          <img src="<%= movie.poster_url %>" class="card-img-top" alt="poster">
          <div class="card-body">
            <p class="card-title"><%= movie.title %> (<%= movie.year %>)</p>
            <%= link_to movie_path(movie.id), method: "delete" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/_search.html.erb
<div class="row">
  <% movies.each do |movie| %>
    <div class="col-lg-3 col-md-4 col-sm-6 py-3 d-flex align-items-stretch justify-content-center">
      <div class="card">
        <img src="<%=movie[:poster_url]%>" class="card-img-top" alt="poster">
        <div class="card-body">
          <p class="card-title"><%= movie[:title] %> (<%= movie[:year] %>)</p>
          <%= simple_form_for([@list, @movie]) do |f| %>
            <%= f.hidden_field :title, value: movie[:title] %>
            <%= f.hidden_field :poster_url, value: movie[:poster_url] %>
            <%= f.hidden_field :year, value: movie[:year] %>
            <button type="submit" class="btn plus">
              <i class="fas fa-plus"></i>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/results.html.erb
<div class="background secondary">
  <%= render "shared/navbar" %>

  <div class="container">

    <div id="search-bar" class="mt-4">
      <%= form_with url: search_list_path, method: :get do |f| %>
        <%= f.text_field :keyword, value: params[:keyword], autofocus: true %>
        <%= f.submit "Search", id: "search-btn" %>
      <% end %>
    </div>

    <div id="results">
    </div>

  </div>
</div>

app/views/movies/search.js.erb
results.innerHTML = "<%= j render partial: 'movies/search', locals: { movies: @movies, list: @list, movie: @movie } %>";

app/views/shared/_navbar.html.erb
<div class="watchlist-navbar">
  <%= link_to root_path do %>
    <div class="logo">
      <%= image_tag "logo.png" %>
      <div>
        <p>Grab your</p>
        <p class="centered">Popcorn</p>
      </div>
    </div>
  <% end %>

  <%= link_to "New watchlist", new_list_path, class:"btn btn-primary" %>
</div>